openapi: 3.0.3
info:
  title: WOO Search
  version: 0.1.0
  description: |2

    The WOO Search API provides an interface to the underlying Elastic Search index.

    Through this API, it's possible to add published documents to the API, or to
    schedule removal of a publication in case it's being retracted. When a supported
    file type is provided, the content of the document itself will also be indexed.

    **Authentication**

    TODO - not implemented yet!

    This API makes use of API Key authentication. All requests must have the
    `Authorization: token <token-value>` HTTP header, where `<token-value>` is
    replaced with the actual API key. API keys are managed in the admin interface,
    and you obtain one by contacting the administrator(s).

    **Audit logging**

    TODO - not implemented yet!

    Audit logging is done at the request level. Clients must send the respective
    HTTP request headers, and the values in those headers will be recorded in the
    audit logs.
  contact:
    url: https://github.com/GPP-Woo/GPP-zoeken
    email: support@maykinmedia.nl
  license:
    name: EUPL
    url: https://github.com/GPP-Woo/GPP-zoeken/blob/main/LICENSE.md
paths:
  /api/v1/documenten:
    post:
      operationId: documentenCreate
      description: Indexeer de document metadata van de Register API in Elasticsearch.
      summary: Indexeer document metadata
      tags:
      - index
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentIndex'
        required: true
      security:
      - tokenAuth: []
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CeleryTaskId'
          description: ''
  /api/v1/documenten/{uuid}:
    delete:
      operationId: documentenDestroy
      description: |-
        Verwijder de document data van de index.
        Merk op dat dit een achtergrond taak inplant om de data te verwijderen.
      summary: Verwijder document van de index.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - index
      security:
      - tokenAuth: []
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CeleryTaskId'
          description: ''
  /api/v1/publicaties:
    post:
      operationId: publicatiesCreate
      description: Indexeer de publicatie metadata van de Register API in Elasticsearch.
      summary: Indexeer publicatie metadata
      tags:
      - index
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Publication'
        required: true
      security:
      - tokenAuth: []
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CeleryTaskId'
          description: ''
  /api/v1/publicaties/{uuid}:
    delete:
      operationId: publicatiesDestroy
      description: |-
        Verwijder de publicatie data van de index.
        Merk op dat dit een achtergrond taak inplant om de data te verwijderen.
      summary: Verwijder publicatie van de index.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      tags:
      - index
      security:
      - tokenAuth: []
      responses:
        '202':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CeleryTaskId'
          description: ''
  /api/v1/search:
    post:
      operationId: search
      description: Zoek de publicatie en/of documenten records.
      summary: Zoek
      tags:
      - search
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Search'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchResponse'
          description: ''
components:
  schemas:
    CeleryTaskId:
      type: object
      properties:
        taskId:
          type: string
          format: uuid
      required:
      - taskId
    Document:
      type: object
      properties:
        uuid:
          type: string
        publicatie:
          type: string
          description: De unieke identificatie van de publicatie.
        informatieCategorieen:
          type: array
          items:
            $ref: '#/components/schemas/InformatieCategorie'
          description: De aanwezige categorie informatie van de publicatie die aan
            de product vast hangt.
        publisher:
          allOf:
          - $ref: '#/components/schemas/Publisher'
          description: De organisatie die de publicatie van dit document heeft gepubliceerd.
        identifier:
          type: string
          default: ''
          description: De (primaire) unieke identificatie.
          maxLength: 255
        officieleTitel:
          type: string
          maxLength: 255
        verkorteTitel:
          type: string
          default: ''
          maxLength: 255
        omschrijving:
          type: string
          default: ''
        creatiedatum:
          type: string
          format: date
          description: De datum waarop het document ontstaan is. Niet te verwarren
            met de registratiedatum - de creatiedatum valt typisch *voor* de registratiedatum.
        registratiedatum:
          type: string
          format: date-time
          description: Systeemdatum en -tijd wanneer het document geregistreed was
            in de GPP-Publicatiebank. Niet te verwarren met de creatiedatum van de
            publicatie, die typisch *voor* de registratiedatum valt.
        laatstGewijzigdDatum:
          type: string
          format: date-time
          description: Systeemdatum en -tijd wanneer het document laatst gewijzigd
            is in de GPP-Publicatiebank.
      required:
      - creatiedatum
      - informatieCategorieen
      - laatstGewijzigdDatum
      - officieleTitel
      - publicatie
      - publisher
      - registratiedatum
      - uuid
    DocumentIndex:
      type: object
      properties:
        uuid:
          type: string
        publicatie:
          type: string
          description: De unieke identificatie van de publicatie.
        informatieCategorieen:
          type: array
          items:
            $ref: '#/components/schemas/InformatieCategorie'
          description: De aanwezige categorie informatie van de publicatie die aan
            de product vast hangt.
        publisher:
          allOf:
          - $ref: '#/components/schemas/Publisher'
          description: De organisatie die de publicatie van dit document heeft gepubliceerd.
        identifier:
          type: string
          default: ''
          description: De (primaire) unieke identificatie.
          maxLength: 255
        officieleTitel:
          type: string
          maxLength: 255
        verkorteTitel:
          type: string
          default: ''
          maxLength: 255
        omschrijving:
          type: string
          default: ''
        creatiedatum:
          type: string
          format: date
          description: De datum waarop het document ontstaan is. Niet te verwarren
            met de registratiedatum - de creatiedatum valt typisch *voor* de registratiedatum.
        registratiedatum:
          type: string
          format: date-time
          description: Systeemdatum en -tijd wanneer het document geregistreed was
            in de GPP-Publicatiebank. Niet te verwarren met de creatiedatum van de
            publicatie, die typisch *voor* de registratiedatum valt.
        laatstGewijzigdDatum:
          type: string
          format: date-time
          description: Systeemdatum en -tijd wanneer het document laatst gewijzigd
            is in de GPP-Publicatiebank.
        downloadUrl:
          type: string
          format: uri
          writeOnly: true
          default: ''
          description: De URL waar het document gedownload kan worden om de inhoudt
            te indexeren.
        fileSize:
          type: integer
          writeOnly: true
          nullable: true
          description: De bestandsgrootte van het document op de harde schijf, in
            bytes.
      required:
      - creatiedatum
      - informatieCategorieen
      - laatstGewijzigdDatum
      - officieleTitel
      - publicatie
      - publisher
      - registratiedatum
      - uuid
    DocumentResult:
      type: object
      properties:
        record:
          allOf:
          - $ref: '#/components/schemas/Document'
          readOnly: true
      required:
      - record
    InformatieCategorie:
      type: object
      properties:
        uuid:
          type: string
        naam:
          type: string
          maxLength: 255
      required:
      - naam
      - uuid
    InformationCategoryBucket:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          description: Het unieke ID die de informatiecategorie aangeeft in GPP-publicatiebank.
        naam:
          type: string
          description: naam van de informatiecategorie
        count:
          type: integer
          minimum: 0
          title: Aantal hits.
          description: Het aantal zoekresultaten de gelinkt zijn aan deze categorie.
      required:
      - count
      - naam
      - uuid
    NaamEnum:
      enum:
      - publication
      - document
      type: string
      description: |-
        * `publication` - Publicatie
        * `document` - Document
    Publication:
      type: object
      properties:
        uuid:
          type: string
        publisher:
          allOf:
          - $ref: '#/components/schemas/Publisher'
          description: De organisatie die de publicatie publiceert.
        informatieCategorieen:
          type: array
          items:
            $ref: '#/components/schemas/InformatieCategorie'
          description: De informatiecategorie verduidelijkt de soort informatie die
            in de publicatie voorkomt.
        officieleTitel:
          type: string
          maxLength: 255
        verkorteTitel:
          type: string
          default: ''
          maxLength: 255
        omschrijving:
          type: string
          default: ''
        registratiedatum:
          type: string
          format: date-time
          description: Systeemdatum en -tijd wanneer de publicatie geregistreed was
            is in de GPP-Publicatiebank.
        laatstGewijzigdDatum:
          type: string
          format: date-time
          description: Systeemdatum en -tijd wanneer de publicatie laatst gewijzigd
            is in de GPP-Publicatiebank.
      required:
      - informatieCategorieen
      - laatstGewijzigdDatum
      - officieleTitel
      - publisher
      - registratiedatum
      - uuid
    PublicationResult:
      type: object
      properties:
        record:
          allOf:
          - $ref: '#/components/schemas/Publication'
          readOnly: true
      required:
      - record
    Publisher:
      type: object
      properties:
        uuid:
          type: string
        naam:
          type: string
          maxLength: 255
      required:
      - naam
      - uuid
    PublisherBucket:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          description: Het unieke ID die de publisher aangeeft in GPP-publicatiebank.
        naam:
          type: string
          description: Naam van de publicerende organisatie.
        count:
          type: integer
          minimum: 0
          title: Aantal hits.
          description: Het aantal zoekresultaten gepubliceerd door deze organisatie.
      required:
      - count
      - naam
      - uuid
    ResultTypeBucket:
      type: object
      properties:
        naam:
          allOf:
          - $ref: '#/components/schemas/NaamEnum'
          title: Result type / index naam
          description: |-
            Geeft de type record/index aan die gevonden is.

            * `publication` - Publicatie
            * `document` - Document
        count:
          type: integer
          minimum: 0
          title: Aantal hits.
          description: De aantal zoekresultaten voor deze specifieke record type/index.
      required:
      - count
      - naam
    ResultTypeEnum:
      enum:
      - '*'
      - publication
      - document
      type: string
      description: |-
        * `*` - Alle
        * `publication` - Publicatie
        * `document` - Document
    Search:
      type: object
      properties:
        query:
          type: string
          default: ''
          description: |-
            Filter records op basis van de meegegeven zoek termen. De zoek query wordt toegevoegd voor de data in de volgende velden (met de prioriteit op basis van de volgorde hieronder):
            - `identifier` **veld alleen aanwezig in Document*
            - `officieleTitel`
            - `verkorteTitel`
            - `omschrijving`
            - `document content` **veld alleen aanwezig in Document*

            U kunt dubbele quotes gebruiken voor het zoeken op exacte matches en 'AND'/'OR' syntax voor complexere queries.
        page:
          type: integer
          default: 1
          description: De pagina nummer binnen de gepagineerde resultaat set.
        pageSize:
          type: integer
          default: 10
          description: De hoeveelheid resultaten die getoond worden per pagina.
        sort:
          allOf:
          - $ref: '#/components/schemas/SortEnum'
          default: relevance
        resultType:
          allOf:
          - $ref: '#/components/schemas/ResultTypeEnum'
          default: '*'
          description: |-
            Welke tabel(len) tot beschikking zijn in de body.

            * `*` - Alle
            * `publication` - Publicatie
            * `document` - Document
        registratiedatumVanaf:
          type: string
          format: date-time
          nullable: true
          description: Filter resultaten op basis van de geregistreerd tijdens of
            na de gegeven datumtijd.
        registratiedatumTot:
          type: string
          format: date-time
          nullable: true
          description: Filter resultaten op basis van de geregistreerd waren voor
            de gegeven datumtijd.
        laatstGewijzigdDatumVanaf:
          type: string
          format: date-time
          nullable: true
          description: Filter resultaten op basis van de de laatste wijzigingsdatum
            op of na de opgegeven datumtijd.
        laatstGewijzigdDatumTot:
          type: string
          format: date-time
          nullable: true
          description: Filter resultaten op basis van de laatste wijzigingsdatum voor
            de opgegeven datumtijd.
        creatiedatumVanaf:
          type: string
          format: date
          nullable: true
          description: Filter documenten die gecreëerd waren na de gegeven datum.
        creatiedatumTotEnMet:
          type: string
          format: date
          nullable: true
          description: Filter documenten die gecreëerd waren voor of op de gegeven
            datum.
        publishers:
          type: array
          items:
            type: string
            format: uuid
            title: publisher-UUID
          description: Filter resultaten gepubliceerd door (een van) de gegeven publishers
            `uuid`.
        informatieCategorieen:
          type: array
          items:
            type: string
            format: uuid
            title: categorie-UUID
          title: informatiecategorieën
          description: Filter resultaten gepubliceerd door (een van) de gegeven categorieën
            `uuid`.
    SearchFacets:
      type: object
      properties:
        resultTypes:
          type: array
          items:
            $ref: '#/components/schemas/ResultTypeBucket'
        publishers:
          type: array
          items:
            $ref: '#/components/schemas/PublisherBucket'
        informatieCategorieen:
          type: array
          items:
            $ref: '#/components/schemas/InformationCategoryBucket'
      required:
      - informatieCategorieen
      - publishers
      - resultTypes
    SearchResponse:
      type: object
      properties:
        facets:
          $ref: '#/components/schemas/SearchFacets'
        count:
          type: integer
        next:
          type: boolean
          readOnly: true
        previous:
          type: boolean
          readOnly: true
        results:
          type: array
          items:
            $ref: '#/components/schemas/SearchResults'
      required:
      - count
      - facets
      - next
      - previous
      - results
    SearchResults:
      oneOf:
      - $ref: '#/components/schemas/SearchResultsDocumentResult'
      - $ref: '#/components/schemas/SearchResultsPublicationResult'
      discriminator:
        propertyName: type
        mapping:
          document: '#/components/schemas/SearchResultsDocumentResult'
          publication: '#/components/schemas/SearchResultsPublicationResult'
    SearchResultsDocumentResult:
      allOf:
      - $ref: '#/components/schemas/SearchResultsShared'
      - $ref: '#/components/schemas/DocumentResult'
    SearchResultsPublicationResult:
      allOf:
      - $ref: '#/components/schemas/SearchResultsShared'
      - $ref: '#/components/schemas/PublicationResult'
    SearchResultsShared:
      type: object
      description: |-
        Polymorphic serializer base class.

        Note that the discriminator field must exist at the same depth as the mapped
        serializer fields for the OpenAPI introspection. See
        https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/ for
        more information. As such, it's not possible to define something like:

        {
            "object_type": "foo",
            "polymorphic_context": {
                <foo-specific fields>
            }
        }

        without explicitly wrapping this in a parent serializer, i.e. -
        ``polymorphic_context`` can not be a PolymorphicSerializer itself, as it requires
        access to the ``object_type`` in the parent scope.
      properties:
        type:
          type: string
      required:
      - type
    SortEnum:
      enum:
      - relevance
      - chronological
      type: string
      description: |-
        * `relevance` - Relevantie
        * `chronological` - Chronologisch
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
externalDocs:
  description: Functional and technical documentation
  url: https://gpp-zoeken.readthedocs.io/
