openapi: 3.0.3
info:
  title: WOO Search
  version: 0.1.0
  description: |2

    The WOO Search API provides an interface to the underlying Elastic Search index.

    Through this API, it's possible to add published documents to the API, or to
    schedule removal of a publication in case it's being retracted. When a supported
    file type is provided, the content of the document itself will also be indexed.

    **Authentication**

    TODO - not implemented yet!

    This API makes use of API Key authentication. All requests must have the
    `Authorization: token <token-value>` HTTP header, where `<token-value>` is
    replaced with the actual API key. API keys are managed in the admin interface,
    and you obtain one by contacting the administrator(s).

    **Audit logging**

    TODO - not implemented yet!

    Audit logging is done at the request level. Clients must send the respective
    HTTP request headers, and the values in those headers will be recorded in the
    audit logs.
  contact:
    url: https://github.com/GPP-Woo/GPP-zoeken
    email: support@maykinmedia.nl
  license:
    name: EUPL
    url: https://github.com/GPP-Woo/GPP-zoeken/blob/main/LICENSE.md
paths:
  /api/v1/documenten/:
    post:
      operationId: documentenCreate
      description: Index the received document metadata from the Register API in Elasticsearch.
      summary: Index document metadata.
      tags:
      - index
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
        required: true
      security:
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
          description: ''
components:
  schemas:
    Document:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        publicatie:
          type: string
          format: uuid
          description: The unique identifier of the publication.
        publisher:
          type: string
          format: uuid
        identifier:
          type: string
          description: The (primary) unique identifier.
          maxLength: 255
        officieleTitel:
          type: string
          maxLength: 255
        verkorteTitel:
          type: string
          maxLength: 255
        omschrijving:
          type: string
        creatiedatum:
          type: string
          format: date
          description: Date when the (physical) document came into existence. Not
            to be confused with the registration timestamp of the document - the creation
            date is typically *before* the registration date.
        registratiedatum:
          type: string
          format: date-time
        laatstGewijzigdDatum:
          type: string
          format: date-time
      required:
      - creatiedatum
      - laatstGewijzigdDatum
      - officieleTitel
      - publicatie
      - publisher
      - registratiedatum
      - uuid
externalDocs:
  description: Functional and technical documentation
  url: https://woo-search.readthedocs.io/
